name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { default: script } = await import('${{ github.workspace }}/actions/ci-example.mjs');
            return await script({ github, context, core, exec, glob, io, fetch, __original_require__ });
  ci2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: actions/ci-example.mjs
  ci3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: typed-actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: actions/ci-example.mjs
